Backwards compatibility for color references
jenkinsci/badge-plugin pull request #200
Opened 2024-10-11 22:12 UTC by cronik

This change improves the backwards compatibility for legacy badge color references that are not jenkins color classes. Colors that reference defined jenkins palette or semantic names are converted to their respective css variable references.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-10-12 07:58 UTC, strangelookingnerd commented
Looking at the code I’m having a hard time to follow what is actually improved here. Would you be able to give some examples of before and after this change?

2024-10-13 17:03 UTC, cronik commented
I have loads of pipelines that use color references from the jenkins palette or semantic names which used to be mapped properly to jenkins color classes.

```groovy
addBadge(icon: 'symbol-star plugin-ionicons-api', color: 'yellow')

addBadge(icon: 'symbol-rocket plugin-ionicons-api', color: 'success')
```

The translation code fails to properly convert these colors to the variable reference so the colors look off or are not found in the case of 'success'.

2024-10-13 19:02 UTC, strangelookingnerd commented
Thanks for the clarification. I was indeed unaware of this incompatibility but I guess it’s reasonable to keep the original behavior. I’ll take a closer look at the code to get this merged soon.

2024-10-15 06:28 UTC, mPokornyETM approved these changes
LGTM

2024-10-15 13:01 UTC, strangelookingnerd requested changes

2024-10-15 13:01 UTC, strangelookingnerd commented on src/test/java/com/jenkinsci/plugins/badge/dsl/LegacyPipelineTest.java
> +        assertEquals("color: #ff0000;", action.getStyle());
Test should cover all valid cases.

2024-10-23 12:33 UTC, strangelookingnerd approved these changes

2024-10-23 12:41 UTC, merged